Add check for multidev environment limit (#119)
* feat: add check for available multidev environments

Prevents deployment if the Pantheon site has reached its multidev environment
limit.

If the limit is reached, the action posts a comment on the corresponding pull
request and aborts the workflow. This avoids unnecessary resource consumption
and provides immediate feedback to the user.

* Potential fix for code scanning alert no. 25: Code injection

Co-authored-by: Copilot Autofix powered by AI <62310815+github-advanced-security[bot]@users.noreply.github.com>

* feat: add message for available multidev environments

* use gh cli natively rather than another action

---------

Co-authored-by: Copilot Autofix powered by AI <62310815+github-advanced-security[bot]@users.noreply.github.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -251,6 +251,44 @@ runs:
             git fetch --unshallow origin
           fi
 
+      - name: Check multidev limit
+        id: check_multidev_limit
+        shell: bash
+        env:
+          PANTHEON_SITE: ${{ inputs.site }}
+        run: |
+          # Check multidev limit
+          set +e
+          MAX_MULTIDEVS=$(terminus site:info "${PANTHEON_SITE}" --field="Max Multidevs")
+          CURRENT_MULTIDEVS=$(terminus multidev:list "${PANTHEON_SITE}" --format=list | grep -vE '^(dev|test|live)$' | wc -l)
+
+          if [ "$CURRENT_MULTIDEVS" -lt "$MAX_MULTIDEVS" ]; then
+            echo "✅You have $((MAX_MULTIDEVS - CURRENT_MULTIDEVS)) multidev environments available."
+            echo "multidev_available=true" >> $GITHUB_OUTPUT
+          else
+            echo "❌ Multidev limit reached."
+            echo "multidev_available=false" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Comment on PR if multidev limit reached
+        if: ${{ inputs.target_env == '' && steps.check_multidev_limit.outputs.multidev_available == 'false' }}
+        shell: bash
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+          PR_NUMBER: ${{ github.event.pull_request.number }}
+        run: |
+          # Comment on PR if multidev limit reached
+          set +e
+          gh pr comment "${PR_NUMBER}" --body "⚠️ Unable to create a Multidev environment for this pull request because the Pantheon Multidev limit for the site has been reached. Please contact Pantheon Support to request an increase in the multidev limit or delete unused Multidev environments."
+          
+
+      - name: Abort deployment if multidev limit reached
+        if: ${{ inputs.target_env == '' && steps.check_multidev_limit.outputs.multidev_available == 'false' }}
+        shell: bash
+        run: |
+          echo "Aborting deployment due to multidev limit reached."
+          exit 1
+
       - name: Deployment Processing
         shell: bash
         id: deploy_to_pantheon
